name: Metrics
on:
  # once per week
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push:
    branches:    
    - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: bullrich
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            python, html, css, javascript, shell
          plugin_languages_skipped: Bullrich/JBullrich, Bullrich/FlixelTut
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_lines: yes
          repositories_forks: yes
          plugin_notable: yes
          plugin_traffic: yes
          # To enable once I set up RSS
          # plugin_rss: yes
          # plugin_rss_source: https://bullrich.dev/feed.xml
